---


- hosts: CSRRouters
  connection: network_cli
  gather_facts: False

  tasks: 
  - name: show run on devices
    ios_command:
      commands:
        - show run
    register: config
    
  - name: Get Current configured NTP servers
    set_fact: _servers="{{config.stdout[0] | regex_findall('^ntp server (\S+)', multiline=true)}}"

  - name: remove old ntp servers
    ios_config:
      lines:
        - "no ntp server {{ item }}"
    with_items: "{{ _servers }}"    

  - name: configure new ntp server
    ios_config:
      lines:
        - ntp server 4.5.6.7


    


    